'use server'

import { createClient } from '@/utils/supabase/server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

// ─── createGameSession ─────────────────────────────────────────────────────
// The host creates a new session for a given world.
// Returns the session invite_code for sharing.
export async function createGameSession(formData: FormData) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('No autorizado')

  const worldId = formData.get('world_id') as string
  const maxPlayers = parseInt(formData.get('max_players') as string) || 4

  if (!worldId) throw new Error('Debes seleccionar un mundo')

  // Create the session — invite_code is auto-generated by the DB trigger
  const { data: session, error } = await supabase
    .from('game_sessions')
    .insert({ world_id: worldId, host_id: user.id, max_players: maxPlayers })
    .select('id, invite_code')
    .single()

  if (error || !session) throw new Error(`Error al crear sesión: ${error?.message}`)

  // Auto-join the host as a session player (they can optionally choose a character later)
  await supabase.from('session_players').insert({
    session_id: session.id,
    user_id: user.id,
  })

  redirect(`/session/${session.invite_code}`)
}

// ─── joinGameSession ───────────────────────────────────────────────────────
// A player joins a session via invite_code, optionally binding a character.
export async function joinGameSession(formData: FormData) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('No autorizado')

  const inviteCode = (formData.get('invite_code') as string)?.toUpperCase().trim()
  const characterId = formData.get('character_id') as string | null

  if (!inviteCode) throw new Error('Introduce un código de invitación')

  // Find the session
  const { data: session, error: sessErr } = await supabase
    .from('game_sessions')
    .select('id, status, max_players')
    .eq('invite_code', inviteCode)
    .single()

  if (sessErr || !session) throw new Error('Código de invitación inválido o sesión no encontrada')
  if (session.status === 'ended') throw new Error('Esta sesión ya ha terminado')

  // Count existing players
  const { count } = await supabase
    .from('session_players')
    .select('*', { count: 'exact', head: true })
    .eq('session_id', session.id)
    .eq('status', 'joined')

  if ((count ?? 0) >= session.max_players) throw new Error('La sesión está llena')

  // Check if already joined
  const { data: existing } = await supabase
    .from('session_players')
    .select('id')
    .eq('session_id', session.id)
    .eq('user_id', user.id)
    .single()

  if (existing) {
    // Re-join (update status back to joined)
    await supabase.from('session_players').update({ status: 'joined', character_id: characterId || null })
      .eq('id', existing.id)
  } else {
    await supabase.from('session_players').insert({
      session_id: session.id,
      user_id: user.id,
      character_id: characterId || null,
    })
  }

  redirect(`/session/${inviteCode}`)
}

// ─── selectCharacterForSession ─────────────────────────────────────────────
// A player (or host) picks their character after joining the lobby.
export async function selectCharacterForSession(sessionId: string, characterId: string) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('No autorizado')

  // Verify the character belongs to this user
  const { data: character } = await supabase
    .from('characters')
    .select('id, world_id')
    .eq('id', characterId)
    .eq('user_id', user.id)
    .single()

  if (!character) throw new Error('Personaje no encontrado')

  await supabase.from('session_players')
    .update({ character_id: characterId })
    .eq('session_id', sessionId)
    .eq('user_id', user.id)

  revalidatePath(`/session/[code]`, 'page')
}

// ─── startGameSession ──────────────────────────────────────────────────────
// Host starts the session — transitions from lobby to active.
export async function startGameSession(sessionId: string) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('No autorizado')

  // Verify host
  const { data: session } = await supabase
    .from('game_sessions')
    .select('id, host_id')
    .eq('id', sessionId)
    .single()

  if (!session || session.host_id !== user.id) throw new Error('Solo el host puede iniciar la sesión')

  // Get first player (host first)
  const { data: players } = await supabase
    .from('session_players')
    .select('user_id')
    .eq('session_id', sessionId)
    .eq('status', 'joined')
    .order('joined_at', { ascending: true })

  const firstPlayerId = players?.[0]?.user_id ?? user.id

  const { error } = await supabase.from('game_sessions').update({
    status: 'active',
    turn_player_id: firstPlayerId,
  }).eq('id', sessionId)

  if (error) throw new Error(`Error al iniciar sesión: ${error.message}`)

  // Redirect all players to the game — we redirect host, others will see via realtime
  const { data: updatedSession } = await supabase
    .from('game_sessions')
    .select('invite_code')
    .eq('id', sessionId)
    .single()
    
  redirect(`/session/${updatedSession?.invite_code}`)
}

// ─── kickPlayerFromSession ─────────────────────────────────────────────────
export async function kickPlayerFromSession(sessionId: string, targetUserId: string) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('No autorizado')

  const { data: session } = await supabase
    .from('game_sessions')
    .select('host_id')
    .eq('id', sessionId)
    .single()

  if (session?.host_id !== user.id) throw new Error('Solo el host puede expulsar jugadores')

  await supabase.from('session_players').update({ status: 'kicked' })
    .eq('session_id', sessionId)
    .eq('user_id', targetUserId)

  revalidatePath(`/session/[code]`, 'page')
}

// ─── advanceTurn ───────────────────────────────────────────────────────────
// Moves the active turn to the next player in join order.
export async function advanceTurn(sessionId: string) {
  const supabase = createClient()

  // Get all active players in join order
  const { data: players } = await supabase
    .from('session_players')
    .select('user_id')
    .eq('session_id', sessionId)
    .eq('status', 'joined')
    .order('joined_at', { ascending: true })

  if (!players || players.length === 0) return

  const { data: session } = await supabase
    .from('game_sessions')
    .select('turn_player_id')
    .eq('id', sessionId)
    .single()

  const currentIdx = players.findIndex(p => p.user_id === session?.turn_player_id)
  const nextIdx = (currentIdx + 1) % players.length
  const nextPlayerId = players[nextIdx].user_id

  await supabase.from('game_sessions').update({ turn_player_id: nextPlayerId }).eq('id', sessionId)
}

// ─── endGameSession ────────────────────────────────────────────────────────
export async function endGameSession(sessionId: string) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('No autorizado')

  const { data: session } = await supabase
    .from('game_sessions').select('host_id').eq('id', sessionId).single()

  if (session?.host_id !== user.id) throw new Error('Solo el host puede finalizar la sesión')

  await supabase.from('game_sessions').update({ status: 'ended' }).eq('id', sessionId)
  redirect('/dashboard')
}
